//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderingManegimentSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail
    {
        [DisplayName("注文番号")]
        public int OrderNo { get; set; }
        public int DetailNo { get; set; }
        public int ItemNo { get; set; }
        [DisplayName("数量")]
        public decimal Quantity { get; set; }
        [DisplayName("希望納期")]
        public System.DateTime DeliveryDate { get; set; }
        [DisplayName("受注日時")]
        public System.DateTime OrderDate { get; set; }

        [DisplayName("ステータス")]
        public string Status { get; set; }
        [DisplayName("顧客ID")]
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
